<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Theme {
	private $theme_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'theme_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'theme_page_init' ) );
	}

	public function theme_add_plugin_page() {
		add_menu_page(
			'theme', // page_title
			'会社情報', // menu_title
			'manage_options', // capability
			'theme', // menu_slug
			array( $this, 'theme_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function theme_create_admin_page() {
		$this->theme_options = get_option( 'theme_option_name' ); ?>

		<div class="wrap">
			<h2>会社情報</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'theme_option_group' );
					do_settings_sections( 'theme-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function theme_page_init() {
		register_setting(
			'theme_option_group', // option_group
			'theme_option_name', // option_name
			array( $this, 'theme_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'theme_setting_section', // id
			'', // title
			array( $this, 'theme_section_info' ), // callback
			'theme-admin' // page
		);

		add_settings_field(
			'op_0', // id
			'会社名', // title
			array( $this, 'op_0_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_1', // id
			'郵便番号', // title
			array( $this, 'op_1_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_2', // id
			'住所', // title
			array( $this, 'op_2_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_3', // id
			'電話番号', // title
			array( $this, 'op_3_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_4', // id
			'受付時間', // title
			array( $this, 'op_4_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);

		add_settings_field(
			'op_5', // id
			'Instagram', // title
			array( $this, 'op_5_callback' ), // callback
			'theme-admin', // page
			'theme_setting_section' // section
		);
	}

	public function theme_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['op_0'] ) ) {
			$sanitary_values['op_0'] = sanitize_text_field( $input['op_0'] );
		}

		if ( isset( $input['op_1'] ) ) {
			$sanitary_values['op_1'] = sanitize_text_field( $input['op_1'] );
		}

		if ( isset( $input['op_2'] ) ) {
			$sanitary_values['op_2'] = sanitize_text_field( $input['op_2'] );
		}

		if ( isset( $input['op_3'] ) ) {
			$sanitary_values['op_3'] = sanitize_text_field( $input['op_3'] );
		}

		if ( isset( $input['op_4'] ) ) {
			$sanitary_values['op_4'] = sanitize_text_field( $input['op_4'] );
		}

		if ( isset( $input['op_5'] ) ) {
			$sanitary_values['op_5'] = sanitize_text_field( $input['op_5'] );
		}
		return $sanitary_values;
	}

	public function theme_section_info() {

	}

	public function op_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_0]" id="op_0" value="%s">',
			isset( $this->theme_options['op_0'] ) ? esc_attr( $this->theme_options['op_0']) : ''
		);
	}

	public function op_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_1]" id="op_1" value="%s">',
			isset( $this->theme_options['op_1'] ) ? esc_attr( $this->theme_options['op_1']) : ''
		);
	}

	public function op_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_2]" id="op_2" value="%s">',
			isset( $this->theme_options['op_2'] ) ? esc_attr( $this->theme_options['op_2']) : ''
		);
	}

	public function op_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_3]" id="op_3" value="%s">',
			isset( $this->theme_options['op_3'] ) ? esc_attr( $this->theme_options['op_3']) : ''
		);
	}

	public function op_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_4]" id="op_4" value="%s">',
			isset( $this->theme_options['op_4'] ) ? esc_attr( $this->theme_options['op_4']) : ''
		);
	}

	public function op_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_option_name[op_5]" id="op_5" value="%s">',
			isset( $this->theme_options['op_5'] ) ? esc_attr( $this->theme_options['op_5']) : ''
		);
	}
}
if ( is_admin() )
	$theme = new Theme();

/*
 * Retrieve this value with:
 * $theme_options = get_option( 'theme_option_name' ); // Array of All Options
 * $op_0 = $theme_options['op_0']; // op
 * $op_1 = $theme_options['op_1']; // op
 * $op_2 = $theme_options['op_2']; // op
 * $op_3 = $theme_options['op_3']; // op
 * $op_4 = $theme_options['op_4']; // op
 * $op_5 = $theme_options['op_5']; // op
 * $op_6 = $theme_options['op_6']; // op
 * $op_7 = $theme_options['op_7']; // op
 * $op_8 = $theme_options['op_8']; // op
 * $op_9 = $theme_options['op_9']; // op
 * $op_10 = $theme_options['op_10']; // op
 * $op_11 = $theme_options['op_11']; // op
 */
